version:  '3'
services:
  datascience-notebook:
    build: 
      context: .
      dockerfile: Dockerfile  
    volumes:
      - ${LOCAL_WORKING_DIR}:/home/jovyan/work
      - ${LOCAL_DATASETS}:/home/jovyan/work/datasets
      - ${LOCAL_SSL_CERTS}:/etc/ssl/notebook
    ports:
      - ${PORT}:8888
    container_name: covid_notebook
    command: "start-notebook.sh \
        --NotebookApp.password=${ACCESS_TOKEN} \
        --NotebookApp.certfile=/etc/ssl/notebook/jupyter.pem"