FROM jupyter/datascience-notebook

RUN echo "install.packages('readr',repos = 'https://cran.rstudio.com')" | R --no-save
RUN echo "install.packages('dplyr',repos = 'https://cran.rstudio.com')" | R --no-save
RUN echo "install.packages('ggplot2',repos = 'https://cran.rstudio.com')" | R --no-save
